### ISSUE TITLE
Install time decisions should be tracked in a cluster-config object

### ISSUE THREAD

**Issue by aaronlevy** [coreos/tectonic-installer#1148]
Operators running the cluster often need to make decisions based on potential install-time decisions. This could be something like "cni-plugin=flannel/canal/calico/weave", or it could be "serviceCidr=10.3.0.0/16".

The two main places this info is currently tracked are:

- config.tf: This is primarily fixed-values associated with a particular version of a tectonic release (e.g. etcd image version).

- [tectonic-config](https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/config.yaml): configMap object which contains a small set of options that a user could set at install time.

I would propose that we start expanding the scope of the tectonic-config to 1) include more values selected at install-time, and 2) restructure for safer long-term use.

An example of this need is to be able to track "alpha" features that were selected at install-time: https://github.com/coreos/tectonic-installer/pull/780#issuecomment-309577275 

What I would propose:
    - Restructure the configMap so that it has a single top-level key. This makes consume the config from a single file much easier. Otherwise every top-level key becomes its own file.
    - Begin versioning the file so that we could support changes to the internal layout of the file over time.
    - Keep the "envelope" of the data simple (e.g. kind+version), and put all data under single key (data)

Current configMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-config
  namespace: tectonic-system
data:
  clusterID: "${cluster_id}"
  installerPlatform: "${platform}"
  certificatesStrategy: "${certificates_strategy}"
  tectonicUpdaterEnabled: "${tectonic_updater_enabled}"
  consoleBaseAddress: "https://${console_base_address}"
  kubeAPIServerURL: "${kube_apiserver_url}"
  tectonicVersion: "${tectonic_version}"
  dexAPIHost: "${identity_api_service}:5557"
```

Strawman proposal:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-config
  namespace: tectonic-system
data:
  tectonic-config:
    version: v1
    type: cluster-config
    data:
        clusterID: "${cluster_id}"
        ...
```

If we were to make a change along these lines the one component that would need to be updated would be the [stats-emitter](https://github.com/coreos/tectonic-installer/blob/068cdfc1da05809139b7fc69d497387efd1cb263/modules/tectonic/resources/manifests/stats-emitter.yaml#L33-L61)

cc @diegs @squat @Quentin-M
