### ISSUE TITLE
Review self-hosted etcd TLS generation and usage

### ISSUE THREAD

**Issue by dghubble** [coreos/tectonic-installer#1186]
Self-hosted etcd TLS support added by bootkube and added in Tectonic differ in their approaches to TLS generation and usage. Upstream, there is an expected layout of etcd TLS assets https://github.com/kubernetes-incubator/bootkube/issues/611, but its unclear which aspects are required and which are not.

Self-hosted etcd TLS changes in [bootkube #582](https://github.com/kubernetes-incubator/bootkube/issues/582) and in [Tectonic #1156](https://github.com/coreos/tectonic-installer/pull/1156).

* Tectonic generates a CA, client cert/key, and peer cert/key which is different from upstream in number and layout. Maybe that's ok, maybe its not. I can't find places in `bootkube start` that require that exact structure.
* Tectonic use different flags on https://github.com/coreos/tectonic-installer/pull/1156/files#diff-1fd1539ef75e6870be501622848f09eb vs https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L966 to accommodate the layout differences.
* `bootkube recover` seems to rely on the etcdMember file layout which is not produced in Tectonic so I don't think recovery will work on Tectonic clusters. https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/recovery/recover.go#L135

I'm not the person to say which parts are right, but the divergence and confusion is something I hope we can discuss and clarify so there are no surprises.

cc @aaronlevy @s-urbaniak @Quentin-M @hongchaodeng

**Comment by s-urbaniak** [comment]
re-ping @hongchaodeng @xiang90 for an advice on the best practice for the installer

**Comment by aaronlevy** [comment]
Also cc @diegs 

Would `bootkube recover` not work in this case? Or does it just extract all needed assets locally (and local path wouldn't matter as long as it knows where to find data in secrets?)

**Comment by s-urbaniak** [comment]
It seems there is a consensus on a simplified directory/file layout outlined in https://github.com/kubernetes-incubator/bootkube/issues/611#issuecomment-311202308. Additionally I referenced the outlined assets to their respective usage targets in https://github.com/kubernetes-incubator/bootkube/issues/611#issuecomment-311587237.

**Comment by aaronlevy** [comment]
etcd-operator has been bumped to v0.4.0 - which has the name changes: https://github.com/coreos/etcd-operator/releases/tag/v0.4.0

So the general plan (hasn't been implemented in bootkube yet though):

Using the cluster-wide CA, generate 3 sets of assets:

```
peer.crt        # Needs both client/server ExtUsage
peer.key
server.crt      # Only needs server ExtUsage
server.key
etcd-client.crt # Only needs client ExtUsage
etcd-client.key
```

The `peer` and `server` keypairs will be used by the etcd members. And the `etcd-client` keypair will be used by the apiserver and the etcd-operator to contact the etcd cluster. Then all CAs will use the cluster wide CA:

```
# All are the same CA cert
peer-ca.crt
server-ca.crt
etcd-client-ca.crt
```

With these assets we need to create the etcd TPR pointing to three secrets:

```yaml
spec:
  ...
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls
```

etcd-peer-tls:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: etcd-peer-tls
type: Opaque
data:
  peer.crt: [...]
  peer.key: [...]
  peer-ca.crt: [...]
```

etcd-server-tls:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: etcd-server-tls
type: Opaque
data:
  server.crt: [...]
  server.key: [...]
  server-ca.crt: [...]
```

etcd-client-tls:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-tls
type: Opaque
data:
  etcd-client.crt: [...]
  etcd-client.key: [...]
  etcd-client-ca.crt: [...]
```

These changes can be done in isolation of bootkube -- we just need to make sure there are no hard-coded expectations in `bootkube recover` so we're confident that we can use it at a later date.

/cc @hongchaodeng
