### ISSUE TITLE
Tectonic-console doesn't correctly display usernames as unicode

### ISSUE THREAD

**Issue by ericchiang** [coreos/tectonic-installer#1517]
BUG REPORT (maybe a feature request?)

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): unknown

## What happened?

A user tried to login with a username that contains unicode characters. The displayed username was mangled.

## What you expected to happen?

The unicode characters to be correctly displayed.

## How to reproduce it (as minimally and precisely as possible)?

Add a static user to the tectonic-login configmap that contains unicode in their username, and login.

```
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "Max Süß"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```

## Anything else we need to know?

This was reported on the dex repo by @steigr https://github.com/coreos/dex/issues/1006

cc @amrutac @kans @ggreer @kyoto
