### ISSUE TITLE
azure: Azure Disk Storage Class kind=Shared no longer works in 1.7.3

### ISSUE THREAD

**Issue by cricci82** [coreos/tectonic-installer#1865]
BUG REPORT

It looks like starting in 1.7.3 we now use Managed Disks for the VMs.  As a result, PVCs using an Azure Disk storage class that has kind=shared (which is the default) fails to mount to the container with the following error:

`AttachVolume.Attach failed for volume "pvc-959c65d5-93f4-11e7-b4c8-000d3a198c68" : Attach volume "kubernetes-dynamic-pvc-959c65d5-93f4-11e7-b4c8-000d3a198c68" to instance "cr-az-cluster-worker-1" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a blob based disk to VM with managed disks is not supported."`

Changing the Storage Class to be of kind=Managed resolves the issue:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: azure-disk-managed
provisioner: kubernetes.io/azure-disk
parameters:
 storageaccounttype: Standard_LRS
 kind: managed
```

## Versions

* Tectonic version:  1.7.3-tectonic.1
* Platform: Azure

## How to reproduce it (as minimally and precisely as possible)?
Create a storage class of kind Shared and then create a deployment with a PVC that uses that storage class as follows:

```
kubectl create -f - <<EOF
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
 storageaccounttype: Standard_LRS
 kind: shared
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: samplepv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: myfrontend
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: myvol
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: myclaim

---
kind: Service
apiVersion: v1
metadata:
  name: pv-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
EOF
```

## Anything else we need to know?
This worked in 1.7.1
