### ISSUE TITLE
kubeconfig could be better formed

### ISSUE THREAD

**Issue by colemickens** [coreos/tectonic-installer#1906]
This is a `kubeconfig` generated by `tectonic-installer` with `azure`:

```
apiVersion: v1
kind: Config
clusters:
- name: colemick1
  cluster:
    server: https://colemick1-api.westus.cloudapp.azure.com:443
    certificate-authority-data: <redacted>
users:
- name: kubelet
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
contexts:
- context:
    cluster: colemick1
    user: kubelet
```

The context is not named, and there is no active context declared in the kubeconfig file.

`kubectl` doesn't mind, but other clients may be sensitive, such as the C# client: https://github.com/kubernetes-client/csharp/issues/24
