### ISSUE TITLE
Enable PodSecurityPolicy by default in Tectonic installations

### ISSUE THREAD

**Issue by joshrosso** [coreos/tectonic-installer#2101]
### Description: PodSecurityPolicy (PSP)

PSP is an admission controller that ensures pods scheduled in the cluster match a policy defined by the cluster administrator. For example, this can prevent pods from running with host networking or in privileged mode.

### Enabling PSPs

Adding PodSecurityPolicy to the list of admission controllers via `kube-apiserver` will enable it. The example below shows the PodSecurityPolicy added to the admission-controller flag.

```yaml
- --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,PodSecurityPolicy
```

### Possible Approach

I understand this change needs to not break existing clusters and also not impede on the bootstrapping process. The following is a **suggestion** on how it could be approached and what my initial PR will contain. I also have an internal (google) doc going with greater detail.

1. Update the `modules/bootkube/resources/manifests/kube-apiserver.yaml` to contain the `PodSecurityPolicy` admission controller. 
2. Add a permissive PSP (full rights / match all) to be used by all cluster-admin users and similar service accounts.
    ```yaml
    apiVersion: extensions/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: system-permissive
    spec:
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        rule: RunAsAny
      runAsUser:
        rule: RunAsAny
      fsGroup:
        rule: RunAsAny
      hostPorts:
      - min: 0
        max: 65535
      volumes:
      - '*'
      allowedCapabilities:
      - '*'
    ```
    > Without this, or a similar policy, bootstrapping will fail to deploy any tectonic pods.

3. Document how to create PSPs and roles that are able to use those PSPs. 
    - The ability to specify which PSP a role snippet that can **use** the PSP `limited-psp-workload-rule` is shown below.
        ```yaml
        - apiGroups:
           - extensions
          resources:
          - podsecuritypolicies
          resourceNames:
          - limited-psp-workload-rule
          verbs:
          - use
        ```

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 647ce84912142a0cd84b7f85427bbe5c619df57a
* Terraform version (`terraform version`): `Terraform v0.10.7`
* Platform (aws|azure|openstack|metal): aws
