### ISSUE TITLE
customized tolerations cannot be saved for daemonset node-exporter

### ISSUE THREAD

**Issue by yuanlinios** [coreos/tectonic-installer#3123]
## What keywords did you search in tectonic-installer issues before filing this one?
toleration, taint

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

### Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash):
```
1.8.7-tectonic.2
```

### Terraform version (`terraform version`):

```
0.10.7
```
### Platform (aws|azure|openstack|metal|vmware):

```
metal
```

### What happened?

customized "tolerations" cannot be saved for daemonset "node-exporter"

### What you expected to happen?

user should be able to add customized taints and tolerations to achieve workload separation/distribution

### How to reproduce it (as minimally and precisely as possible)?

Edit the toleration from kubectl:
```
kubectl -n tectonic-system edit daemonset node-exporter
```
and then add customized tolerations or just change the default tolerations from:
```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
```
to 
```
      tolerations:
      - effect: NoSchedule
        operator: Exists
```
or just edit the yaml from tectonic web console. Save the change. 
After a few minutes the change will be reverted automatically

**Comment by cehoffman** [comment]
This is a feature we need as well. We've changed all the core daemonset manifests to

```yaml
tolerations
- operator: Exists
  effect: NoSchedule
```

To allow custom tolerations for our use while not breaking the nodes from being functioning members of the cluster. The only manifest that is giving us troubles is the node-exporter because of the automatic revert done.
