### ISSUE TITLE
use /var/log/kubernetes/api-server

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#499]
I am concerned about having a bind mount to /var/log into the API server. Did we consider using /var/log/kubernetes/api-server or something instead?

https://github.com/coreos/tectonic-installer/blob/c10fb33624ce0aad08b63cd3618e801234b1db2e/modules/bootkube/resources/manifests/kube-apiserver.yaml#L57

**Comment by chancez** [comment]
What's the actual concern here? That it can see other log files?

**Comment by robszumski** [comment]
@chancez that you have to mount the _entire_ directory into the container

**Comment by chancez** [comment]
The API already has full access to everything's logs (though, using the kubelet API), so I don't see how that's a _new_ concern. It does gain access to some more host level logs I guess, but I don't particularly see that as a huge deal.

**Comment by chancez** [comment]
Also, this is the approach upstream took so I just did the same, but that isn't to say upstream did it correctly.

**Comment by robszumski** [comment]
From @philips 

> it would be nice if all of the logs ended up in a single directory, this will become critical as we create new UIDs

**Comment by philips** [comment]
@chancez link to upstream?

**Comment by chancez** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml#L189-L206

I'd be fine with something like `/var/log/kubernetes`. I don't want to re-use `/var/log/containers` though, because the filenames are too ambiguous to differentiate between normal pod log files, and the audit log files, which makes doing routing and parsing of the records in fluentd more difficult.

**Comment by philips** [comment]
Lets do /var/log/kubernetes/kube-apiserver-audit.log

**Comment by pollosp** [comment]
Hi, 
We are having problems with `/var/log/kubernetes/`. 
Here is our output:
```
$kubectl --kubeconfig=/Users/omar/Downloads/staging-kubectl-config -n kube-system exec -ti kube-apiserver-ssp11 ls /var/log/kubernetes
kube-apiserver-audit.log
$kubectl --kubeconfig=/Users/omar/Downloads/staging-kubectl-config -n kube-system exec -ti fluentd-jhb24 ls /mnt/log/kubernetes
$kubectl --kubeconfig=/Users/omar/Downloads/staging-kubectl-config -n kube-system exec -ti fluentd-jhb24 ls /mnt/log/
btmp        faillog     kubernetes  pods        wtmp
containers  journal     lastlog     sssd
```
Here https://github.com/coreos/tectonic-installer/blob/1.6.2-tectonic.1/modules/bootkube/resources/manifests/kube-apiserver.yaml you are using:

```
volumes:
 - name: var-log-kubernetes
        hostPath:
          path: /var/log/kubernetes
```

```
 volumeMounts:
        - mountPath: /var/log/kubernetes
          name: var-log-kubernetes
          readOnly: false
```

We want to see `kube-apiserver-audit.log` in our fluentd container with the following directories mounted:

```
volumes:
  - name: host-logs
    hostPath:
      path: /var/log/
```
```
 volumeMounts:
   - name: host-logs
     readOnly: true
     mountPath: /mnt/log/
```

But as I paste at de beginning of the comment:
The directory is empty
```
$kubectl --kubeconfig=/Users/omar/Downloads/staging-kubectl-config -n kube-system exec -ti fluentd-jhb24 ls /mnt/log/kubernetes
```
Any idea what it is happening? is that a bug?
