### ISSUE TITLE
Generated kubeconfig from console does not include "extra-scopes"

### ISSUE THREAD

**Issue by ericchiang** [coreos/tectonic-installer#617]
Currently, users are required to specify any extra scopes outside of "openid email profile" when refreshing an ID Token. For example, if you request "openid email profile groups", unless otherwise specified kubectl will only send "openid email profile" when refreshing, omitting "groups".

Some upstream details here: https://github.com/kubernetes/kubernetes/issues/37875

Until that issue is fixed, when generating a kubeconfig the auth-provider config needs to include "extra-scopes: groups", which console currently doesn't do.

```yaml
users:
- name: tectonic-oidc
  user:
    auth-provider:
      config:
        client-id: tectonic-kubectl
        client-secret: (omittied)
        id-token: (omitted)
        idp-certificate-authority-data: (omitted)
        refresh-token: (omitted)
        idp-issuer-url: (omitted)
        extra-scopes: groups
      name: oidc
```

This was observed by @joshrosso here https://github.com/coreos/dex/issues/940

cc @rithujohn191 @amrutac
