### ISSUE TITLE
aws loadbalancer service created on cluster built with tectonic only available in one az

### ISSUE THREAD

**Issue by rhenretta** [coreos/tectonic-installer#786]
I had some back and forth with the people over in the kubernetes repo because I wasn't convinced that it was a tectonic issue, but apparently it is. 

https://github.com/kubernetes/kubernetes/issues/28586#issuecomment-302784146

What is happening is when I create a service type loadbalancer on the tectonic managed cluster, it ends up creating the load balancer in only 1 AZ, so nodes in other AZs show up as out of service.  I can manually add the AZs to the ELB, but that defeats the purpose.

I'm running version 1.6.2

Service is create as such:
```
apiVersion: v1
kind: Service
metadata:
  name: taggenerator-staging
  namespace: taggenerator
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: TagGenerator-Staging
  ports:
    - name: web-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: service-http
      protocol: TCP
      port: 8080
      targetPort: 8080
```

The relevant parts of the ELB are: 
```
$ aws elb describe-load-balancers 
{
    "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-94a3eca8"
            ], 
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 30177, 
                        "LoadBalancerPort": 8080, 
                        "Protocol": "TCP", 
                        "InstanceProtocol": "TCP"
                    }, 
                    "PolicyNames": []
                }, 
                {
                    "Listener": {
                        "InstancePort": 30019, 
                        "LoadBalancerPort": 80, 
                        "Protocol": "TCP", 
                        "InstanceProtocol": "TCP"
                    }, 
                    "PolicyNames": []
                }
            ], 
            "HealthCheck": {
                "HealthyThreshold": 2, 
                "Interval": 10, 
                "Target": "TCP:30019", 
                "Timeout": 5, 
                "UnhealthyThreshold": 6
            }, 
            "BackendServerDescriptions": [], 
            "Instances": [
                {
                    "InstanceId": "i-0b51b05e919ca20e4"
                }, 
                {
                    "InstanceId": "i-0b590a3b795678a35"
                }, 
                {
                    "InstanceId": "i-0fe6037ca0aa43279"
                }
            ], 
            "Policies": {
                "LBCookieStickinessPolicies": [], 
                "AppCookieStickinessPolicies": [], 
                "OtherPolicies": []
            }, 
            "AvailabilityZones": [
                "us-east-1e"
            ], 
            "Scheme": "internet-facing", 
        }
    ]
}
```
So, while there are 3 instances, only 2 are in service because the third is in another AZ.  My cluster has 4 AZs that nodes can live on, but only us-east-1e is available.  If all my nodes end up in different AZs, then the service will fail.
