### ISSUE TITLE
ServiceMonitor: add for tectonic Ingress Controller

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#802]
**Feature Request** Having a ServiceMonitor for the Tectonic Ingress controller is really convenient for debugging basic stuff about its health.

e.g. `rate(nginx_nginx_all_total_requests{job="tectonic-lb"}[1m])` 

This is the ServiceMonitor that would need to be deployed into `tectonic-system`.

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: tectonic-ingress-controller
  labels:
    k8s-app: tectonic-lb
spec:
  selector:
    matchLabels:
      k8s-app: tectonic-lb
  endpoints:
  - port: health
```
