### ISSUE TITLE
etcd-operator with backup fails to start with permission denied to mkdir /.aws

### ISSUE THREAD

**Issue by BdeUtra** [coreos/tectonic-installer#959]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): https://github.com/coreos/tectonic-installer/releases/tag/1.6.4-tectonic.1-rc.3
* Terraform version (`terraform version`): Terraform v0.9.6-dev (fcdf494cffc06aac027f6cf904647051ab6d5015+CHANGES)
* Platform (aws|azure|openstack|metal): AWS

## What happened?
When backup args are passed in to etcd-operator it fails to start with 

`level=fatal msg=controller Run() ended with failure: mkdir /.aws: permission denied`

I suspect this is because it no longer runs as root (see https://github.com/coreos/tectonic-installer/commit/9dd1657a025642cba0b07ac4e495b607817ff03c) and therefore it fails here https://github.com/coreos/etcd-operator/blob/master/pkg/controller/s3.go#L43

## What you expected to happen?
Etcd-operator to start normally.

## How to reproduce it (as minimally and precisely as possible)?

1. Edit `modules/bootkube/resources/experimental/manifests/etcd-operator.yaml` to include backup-aws-secret and backup-aws-config and the operator backup args:
```yaml
apiVersion: v1
data:
  credentials: ....
kind: Secret
metadata:
  name: etcd-backup-aws
  namespace: kube-system
type: Opaque

---

apiVersion: v1
data:
  config: |
    [default]
    region = eu-west-1
kind: ConfigMap
metadata:
  name: aws-region
  namespace: kube-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    k8s-app: etcd-operator
  name: etcd-operator
  namespace: kube-system
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        k8s-app: etcd-operator
    spec: 
      containers: 
        - env: 
            - name: MY_POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
          image: ${etcd_operator_image}
          name: etcd-operator
          command:
          - /usr/local/bin/etcd-operator
          - --backup-aws-secret=etcd-backup-aws
          - --backup-aws-config=aws-region
          - --backup-s3-bucket=<insert_bucket_name>
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```

2. Run terraform apply as per docs

## Anything else we need to know?
I've also changed `modules/bootkube/resources/experimental/etcd/migrate-etcd-cluster.json`
to include .spec.backup as below:
```yaml
    "backup": {
        "backupIntervalInSecond": 120,
        "maxBackups": 5,
        "storageType": "S3"
    }
```
but I don't think it matters to this issue.

**Comment by BdeUtra** [comment]
Removing 
```yaml
securityContext:
        runAsNonRoot: true
        runAsUser: 65534
```
from the etcd-operator does allow it to start normally.
